### PR TITLE
[WIP] use go mod and remove vendors

### PR DESCRIPTION
**Pull request by qianlei90**
### Description of the change

- This PR just update go mod and remove vendors: `rm -rf vendor/ && go mod tidy`
- `make test` passed

### Applicable issues

  - fixes #

### CODE REVIEW

**Comment by andresmgot** [comment]
Thanks for the PR @qianlei90, actually since we are using go mod, we should be able to remove the `vendor/` folder and avoid huge PRs like this one. Can you give it a try?

**Comment by qianlei90** [comment]
done. PTAL.

**Comment by andresmgot** [comment]
You will need to remove lines like this one: https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeops/Dockerfile#L6 for the different services

**Review by andresmgot — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
