### PR TITLE
Avoid CRD deletion when upgrading

### LINKED ISSUE #800: Upgrading the Kubeapps chart deletes the apprepositores CRD
Somehow the upgrade process is deleting the apprepositories CRD for me:

```
▶ helm install --name kubeapps  --namespace kubeapps bitnami/kubeapps
NAME:   kubeapps
LAST DEPLOYED: Fri Nov  9 13:18:13 2018
NAMESPACE: kubeapps
STATUS: DEPLOYED
...
▶ kubectl get crd
NAME                           CREATED AT
apprepositories.kubeapps.com   2018-11-09T12:14:36Z
▶ helm upgrade --namespace kubeapps kubeapps bitnami/kubeapps
Release "kubeapps" has been upgraded. Happy Helming!
LAST DEPLOYED: Fri Nov  9 13:18:47 2018
NAMESPACE: kubeapps
STATUS: DEPLOYED
...
▶ kubectl get crd
No resources found.
```

### PR DESCRIPTION
**Pull request by andresmgot**
Fixes #800

### CODE REVIEW

**Comment by arapulido** [comment]
What versions of the chart are affected by this issue?

**Comment by andresmgot** [comment]
The code related to the CRD was changed in the version `0.3.0` but I doubt this is an issue since then (Aug 23) we should have noticed before. Let's see if @migmartri or @prydonius know something else about this issue.

**Comment by migmartri** [comment]
Thank you @andresmgot for noticing the issue and fixing it.

> The code related to the CRD was changed in the version 0.3.0 but I doubt this is an issue since then (Aug 23). We would have noticed before.

I am afraid that the issue might have been actually there and this is the reason I have not noticed it https://github.com/kubeapps/kubeapps/issues/800#issuecomment-437521909

There is a report of a potential instance of the error here https://github.com/kubeapps/kubeapps/issues/625 and I saw it once but could not reproduce.

**Comment by andresmgot** [comment]
I understand the issue. In any case, CRDs are cluster wide so in any case, several instances of Kubeapps needs to be upgraded if we change the version of the CRD. I am landing this PR to fix the original issue. Thanks for the input!

**Pull request merged**
