### PR TITLE
Update yarn and go deps

### LINKED ISSUE #2228: Bump up old image versions (nginx, oauth2proxy, etc)
We already have this as part of our release instructions, it's just been skipped sometimes.

I've done the images in #2224 , but I've not done the frontend packages, they'll take a little more work.

### PR DESCRIPTION
**Pull request by andresmgot**
### Description of the change

Closes #2228

Updated NPM deps (yarn upgrade) and go deps (go get -u).

I had to fix a Go test, apart from that, smooth upgrade.

### CODE REVIEW

**Review by antgamdia — APPROVED** [review]
Great! Happy to see the new versions!!

**Comment by absoludity** [comment]
I don't understand why we're not worrying about the warnings shown during `yarn upgrade`:
```
root@685a723d05e7:/app# yarn upgrade
yarn upgrade v1.22.4
[1/4] Resolving packages...
warning @types/moxios > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
warning @types/vfile@4.0.0: This is a stub types definition. vfile provides its own type definitions, so you do not need this installed.
warning @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
warning diff2html > hogan.js > mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning react-jsonschema-form > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-jsonschema-form > @babel/runtime-corejs2 > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning enzyme > cheerio > cheerio-select-tmp@0.1.1: Use cheerio-select instead                                                    
warning jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()   
warning jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer supported
warning jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > @jest/environment > @jest/transform > jest-haste-map > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > @jest/fake-timers > jest-message-util > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > @jest/fake-timers > jest-message-util > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning node-sass-chokidar > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-sass-chokidar > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > fsevents@2.1.2: "Please update to latest v2.3 or v2.2"                                                     
warning react-scripts > eslint-loader@3.0.3: This loader has been deprecated. Please use eslint-webpack-plugin                     
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning react-scripts > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning react-scripts > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated       
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi@15.1.1: Switch to 'npm install joi'                     
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

Some are devDependencies only, but this doesn't mean they are not a security threat - it just means they're not a security threat to the bundled app, they can still affect us. But not all are dev dependencies. For example, we're using quite an old version of `diff2html` which depends on no-longer supported modules (as mentioned above). Why aren't we updating our version to "^3.1.18" or similar?

**Comment by antgamdia** [comment]
I don't know either, but I guess the aim of this PR was solely to address minor and patch upgrades. I suppose we will upgrade the deprecated deps in a follow-up PR once we have defined a protocol for performing the upgrades (https://github.com/kubeapps/kubeapps/issues/2237).

Anyway, 100% agree we should bump up these dependencies.

**Comment by andresmgot** [comment]
That's yet another issue (apart from the moxios one, they are not security issues)

**Pull request merged**
