### PR TITLE
[5/n] UI changes - AvailablePackageDetail

### PR DESCRIPTION
**Pull request by antgamdia**
Please refer to https://github.com/kubeapps/kubeapps/issues/3165#issue-948121014 for further details 

### Applicable issues

  - fixes #

### CODE REVIEW

**Comment by absoludity** [comment]
It looks like this includes all the previous changes? Maybe it's just a matter of either waiting until those are landed in master? Let me know.

**Comment by antgamdia** [comment]
> It looks like this includes all the previous changes? Maybe it's just a matter of either waiting until those are landed in master? Let me know (when you're back).

I wrongly target `master` and not my `3085-useNewAPI` base branch, sorry for the noise.
However, still not ready for review (I should have marked it -and the rest- as a draft indeed)

**Comment by antgamdia** [comment]
e2e tests still not passing. I'm sure it should be some silly I'm missing, but dunno now :(
I've tried updating the chart version we upload to chartmusseum from 7.3.15/16 to 8.6.2/3. I assumed it was failing because this version is no longer present on the "available pkg versions" response. However, still not passing.

image


What the CI detected and it was an actual error was a problem while upgrading. We weren't refreshing the package after rolling back (now it's fixed).

If you could have a look at the e2e failure, I'd be great, @absoludity

Besides this problem, the only remaining thing is merging this PR into `3085-useNewAPI` and, then this one into the main branch. I'm gonna create the PR 3085->master, so that you can merge whenever you want.
During (my) morning, I'll perform more manual tests and trigger the release (I've updated our demo server with the latest version).

**Comment by absoludity** [comment]
Hi Antonio. What is actually for review here, or is this the aggregation of all the other changes? Also, I can take a look at why CI isn't passing (why the filtering is resulting in no apps to show) as well as ensuring we get screenshots.

**Comment by antgamdia** [comment]
>  What is actually for review here, or is this the aggregation of all the other changes?

Well, as we wanted to trigger the release as soon as we could, I merged the new changes ("installed applications summaries" view, "available package details" view, "installing/upgrading package" view, "installed application details" view) and I was going to merge it into 3085 (which is targeting master) to get the final green light from you.

Now we are facing some e2e minor issues and I jumped into your (early) tz, perhaps it's better for you to have a look first at https://github.com/kubeapps/kubeapps/pull/3271 (I can revert it if you want, to ease the review process).

But, honestly, I don't know how to review a `+6,102 −9,933` PR... I would like to have split changes but since we have been fixing tests in a rush... I don't know a better approach.
(Ideally, I had my 4.1...4.6 PRs, but it would have implied backporting the fixed tests for the old model (but w/o using containers), extra work in an extra time we don't have :S)

**Comment by antgamdia** [comment]
> I assumed it was failing because this version is no longer present on the "available pkg versions" response. However, still not passing.

FWIW, I've added in our demo server a private repo pointing to a demo harbor instance, and  the repo disambiguation is not working :(   (clicking not making any effect, also, empty string for the pkg name)

image

Code at /dashboard/src/components/AppUpgrade/AppUpgrade.tsx

Don't know if it's related, but wanted to let you know. I can have a look at it tomorrow.

**Comment by absoludity** [comment]
> Don't know if it's related, but wanted to let you know. I can have a look at it tomorrow.

Yeah, I'm setting up local ci to test and fix right now, but will need to prep other things for today too. Let's not rush if it's not ready, but keep working consistently with the time we have :)

**Comment by antgamdia** [comment]
Fixing the repo selection from:

(No message was return if the package wasn't being found)
image

https://user-images.githubusercontent.com/11535726/131531701-2cc9d7b2-ad1e-45b3-88ca-e322155c3a9b.mp4

**Comment by antgamdia** [comment]
Merging to `3085-useNewAPI` as CI is FINALLY passing.

**Pull request merged**
