### PR TITLE
Update frontend deps before release.

### PR DESCRIPTION
**Pull request by absoludity**
### Applicable issues

  - fixes #

### CODE REVIEW

**Comment by absoludity** [comment]
I've gone ahead with the release without this for now. We appear to have a lot of frontend packages at versions that are no longer supported and should be updated. Let's do this as part of the next release?

**Comment by andresmgot** [comment]
I guess so

**Comment by antgamdia** [comment]
I'm also concerned about the hardcoded import of Clarity ([Component](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/Layout/Clarity.tsx#L35) and [Dockerfile](https://github.com/kubeapps/kubeapps/blob/master/dashboard/Dockerfile#L9)).
Dockerfile manually adds Clarity ui@4.0.1 whereas the package.json is also declaring [^2.3.4](https://github.com/kubeapps/kubeapps/blob/fee5e8130a5aaf9c088d0e884e4046ab4713550b/dashboard/package.json#L10), which is definitely incompatible with versions > 2.x.x.

For a newcomer dev it is a bit misleading to have to manually add a dependency that is apparenly included in the package.json.
Perhaps we can point the import to `import "../../../node_modules/@clr/ui/clr-ui.min.css";` instead of `import "../../clr-ui.min.css";`. IMHO, this will be compatible with both online / offline approaches.

**Comment by andresmgot** [comment]
Good catch @antgamdia! feel free to send a PR to remove that ambiguity (we can also remove the references to `hex.min.css`)

**Comment by absoludity** [comment]
Indeed. Good catch . I'll close this PR since it's way out of date now anyway - I had checked for a quick update before a release but that wasn't possible.

**Pull request closed without merging**
