### PR TITLE
add search component to pages

### LINKED ISSUE #241: Add search box and filters in Apps, Charts, Functions and Service Instances lists
There is no more search capability in the Charts view, we need to add it back.

### PR DESCRIPTION
**Pull request by prydonius**
screen shot 2018-05-14 at 09 28 12

fixes #241

### CODE REVIEW

**Comment by Angelmmiguel** [comment]
@prydonius please, could you align the search box to the right?

**Comment by prydonius** [comment]
@Angelmmiguel this doesn't work well on the pages with buttons like "New App", what do you think?

**Comment by sameersbn** [comment]
lgtm! 
re: the searchbox. what do you think about 
kubeapps dashboard

**Comment by prydonius** [comment]
@sameersbn that looks a bit strange to me. Let's merge this as-is for now and we can revisit the positioning later.

**Pull request merged**
