### PR TITLE
Added timeout parameter for Helm operations (#3604)

### PR DESCRIPTION
**Pull request by castelblanque**
Signed-off-by: Rafa Castelblanque <rcastelblanq@vmware.com>

### Description of the change

Helm has a default timeout for operations set to 300 seconds.
When installing a Helm chart, if there is any pre/post installation hook taking more than 300 seconds, the process will fail.

This PR allows to set a timeout for Helm operations from the Kubeapps chart values.

### Benefits

Helm charts installation can now take more than 300 seconds overall :)

### Possible drawbacks

Allowing to increase timeout for Helm operations might lead to scenarios where other timeouts kick in before, e.g. Helm timeout = 200s and Nginx timeout set to 60s ?

### Applicable issues

- Ref #3604

### Additional information

### CODE REVIEW

**Comment by castelblanque** [comment]
Writing the tests is a bit tricky, as the timeout is handled by Helm's kube client, and usually in tests the kube client is entirely mocked using `FailingKubeClient` and no logic for timeouts exists there.
Any ideas on how to test it? Some work [done here](https://github.com/kubeapps/kubeapps/blob/3604-helm-timeout/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/create_test.go#L202).

**Comment by absoludity** [comment]
Thanks Rafa. Great work so far. Sorry for the essay here:

> Writing the tests is a bit tricky, as the timeout is handled by Helm's kube client, and usually in tests the kube client is entirely mocked using `FailingKubeClient` and no logic for timeouts exists there. Any ideas on how to test it? Some work [done here](https://github.com/kubeapps/kubeapps/blob/3604-helm-timeout/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/create_test.go#L202).

I think you already mentioned, but the [fake Helm kube client completely ignores the timeout](https://github.com/helm/helm/blob/98c4ccf29b6e13568349fe57f5bfd3607ac286e8/pkg/kube/fake/printer.go#L77). You've created your own fake which can actually use the timeout when set, but it looks like you're doing an integration test which is actually going to wait for seconds. I think this road is tricky because we'd really need a proper integration test with a chart that has a hook which will run for a configurable time so that we can cause it to timeout?

But in terms of a unit test here, I think (personally, others may disagree) that we'd only want to test to the border of our contract with helm. With this in mind, you've tested the config parsing already (great), we just want to ensure that a server configured with the timeout results in a helm client that is passed that same timeout, I think? (The helm project is responsible for the contract of what happens with that timeout).

But easier said than done. I was then a bit stumped as to how we could do that, because the agent just returns the release, we have no way to test the internal state of the helm command there. I went down the rabbit-hole that you may have already traveled of seeing if we could have a hook defined for the test chart so we could trigger the preinstall hook and use that to record the timeout used, but it's quite complicated to do so.

The only solution I can see to verify this is to split it into two separate unit tests, one for the plugin's CreateRelease, and one for the agent code, to verify that the value is passed through to helm.

To first test the plugin, we could update the server struct so that it has a field for the CreateRelease function which is initialised in `NewServer` to the `agent.CreateRelease` function, but in tests we explicitly set it to a dummy function that just records the timeout used. Then test here that calling the server (configured with a timeout) `CreateInstalledPackage` function results in a call to the `CreateRelease` function with the expected arguments (including the timeout).

Then secondly to unit-test the code in the `agent` module, extract the lines which create the `cmd` object to a private function of the module that returns the `cmd`, and unit-test that to show that the `cmd.Timeout` is set with the value from the argument. Not perfect.

All in all, it's not a great situation testing-wise that you've found here (and the solution outlined isn't that great either, just testing the arguments passed). So I'm OK with your branch just having the parsing test that you've done, or if you want to give the above a go, that's fine too, but totally up to you.

**Comment by castelblanque** [comment]
The way to approach testing is always an open discussion in projects 😄 
When possible, I like to create integration tests to be sure that the whole flow works as expected end to end.
For this case, probably it is not worth the effort to create complete integration tests.

>The only solution I can see to verify this is to split it into two separate unit tests, one for the plugin's CreateRelease, and one for the agent code, to verify that the value is passed through to helm.

I totally agree with your approach for testing here, makes sense.
Let's stick to the unit tests with extracted Helm command creation and CreateRelease function variable.

Many thanks Michael!

**Review by absoludity — APPROVED** [review]
> When possible, I like to create integration tests to be sure that the whole flow works as expected end to end.

Yeah, that'd be ideal... I just can't see how to do that with the provided testing fakes from Helm (that ignore the timeout). The only option would be to add an actual e2e test specifically for this, but that becomes very heavy-weight.

Thanks for the updates!

**Pull request merged**
