### PR TITLE
Add GetNamespaceNames, CreateNamespace and CheckNamespaceExists to resources plugin

### PR DESCRIPTION
**Pull request by absoludity**
Signed-off-by: Michael Nelson <minelson@vmware.com>

### Description of the change

This PR adds the definition only to the resource.proto. Subsequent PRs will add the implementation for the Check and Create methods.

### Benefits

Allows implementation of methods required for two call-sites in the dashboard that currently talk directly to the K8s API server.

### Applicable issues

- Ref #3896

### CODE REVIEW

**Comment by absoludity** [comment]
Trying to find out which upgrade of `ts-proto` has introduced a change in the generated typescript code that doesn't pass lint (due to `not all paths return a value`). Seems to have happened recently but not in this PR.

**Comment by castelblanque** [comment]
Excellent! Looking forward to having the `proto` API code automatically generated and out of the PRs 😃

**Comment by absoludity** [comment]
> Excellent! Looking forward to having the `proto` API code automatically generated and out of the PRs smiley

Given this change is just the proto (and generated files), and you approved the subsequent one with the implementation, and didn't have any feedback other than the above for this, I'm going to assume that was a +1 :)

**Comment by absoludity** [comment]
> > Excellent! Looking forward to having the `proto` API code automatically generated and out of the PRs smiley
> 
> Given this change is just the proto (and generated files), and you approved the subsequent one with the implementation, and didn't have any feedback other than the above for this, I'm going to assume that was a +1 :)

Woops, sorry, you hadn't actually added a +1 to the next one either. I'll not land that until then.

**Comment by castelblanque** [comment]
I had just added a comment which I thought was published, but it was part of the PR review that wasn't sent 😄 
Sorry!

**Pull request merged**
