### PR TITLE
Catch error when parsing YAML manifests

### PR DESCRIPTION
**Pull request by andresmgot**
Fixes: #635

Add `manifestError` to the AppView state for setting it if the manifest cannot be parsed:

screen shot 2018-09-18 at 17 38 15

### CODE REVIEW

**Comment by migmartri** [comment]
I am not sure if we want to add specific error handling for this case instead of eventually a global errorBoundary. About this specific case, did you take a look at this comment? https://github.com/kubeapps/kubeapps/issues/636#issuecomment-421160771

They are orthogonal issues meaning that both make sense but once the parser is relaxed, errors in the parsing might be scarce and hence this specific error handling not needed. WDYT?

**Comment by prydonius** [comment]
@migmartri I agree, and especially since we know that this blob of YAML has gone through both Helm and Kubernetes, it really _should_ be parseable (unless someone has modified the state in the ConfigMap to make it not so).

**Comment by andresmgot** [comment]
I thought that "Our error handling here seems deficient and misleading, we need to improve it. #635" meant to catch the error here and that was the purpose of the issue. If the goal was to refactor how we handle errors I have already opened #654 with a more detailed description. Should we close this PR and #635?

**Comment by migmartri** [comment]
> I thought that "Our error handling here seems deficient and misleading, we need to improve it. #635" meant to catch the error here and that was the purpose of the issue. If the goal was to refactor how we handle errors I have already opened #654 with a more detailed description. Should we close this PR and #635?

Sorry for the confusion @andresmgot. What I meant with that sentence is that we need to tell the user that there was an error, not showing a partially rendered error. I believe that this could be done using https://reactjs.org/docs/error-boundaries.html at a higher level.

In this patch, you solved that, you are right, but just for the case in which there was a yaml parsing error. Which it would be fine if it was not because we could potentially prevent from this error from happening in the first place. So my argument is about 1: Not handle this specific error but change the yaml parser behavior, 2: Look into a generic way of handling runtime errors via errorBoundaries.

To your question. I'd close this PR and just closed 535 since I have created a generic error handling task https://github.com/kubeapps/kubeapps/issues/657

**Pull request closed without merging**
