### PR TITLE
Upgrade ts-proto with fix for noImplicitReturns.

### PR DESCRIPTION
**Pull request by absoludity**
Signed-off-by: Michael Nelson <minelson@vmware.com>

### Description of the change

Replaces #3906 . The current version of `ts-proto` which we use generates typescript that fails our typescript lint checks. This means that any new PR which needs to generate, fails to pass CI.

cc @antgamdia I'm not 100%, but it looks like you may have manually updated the generated content in [this commit](https://github.com/kubeapps/kubeapps/pull/3894/commits/dcf07cc2b4b2ea4c91267da647d21a9b0d5cd273) so that it would pass? I thought of doing the same but we need to be able to work with the generated content.

I've created an issue upstream to see if it's something that may be fixed upstream, in https://github.com/stephenh/ts-proto/issues/432

For now I've just disabled the `noImplicitReturns` check. Longer term we should re-enable this and also generate these files during our build process so that this is caught immediately when the ts-proto package was upgraded (see #3908)

### Benefits

We can continue to modify protobuf files without breaking the build.

### Applicable issues

- ref #3896

### CODE REVIEW

**Comment by boukeversteegh** [comment]
Hey @absoludity , thanks for opening an issue in ts-proto, we will fix the issue there.

In the meantime, I thought the following might be helpful. When generated code doesn't match your project's linting rules, you could also disable linting on the generated code, or exclude a violated rule for a particular folder or file. That way you won't be blocked and don't need to disable the rule for your whole project. It's also handy for cases where the rules of the two projects contradict each other, and it cannot be fixed upstream.

For example, you could do this:

```js
// .eslintrc.js
module.exports = {
  // exclude entire directory from linting
  ignorePatterns: ['src/lib/**'],
  overrides: [
    // disable specific rule in directory
    {
      files: ['somedirectory/**/*.ts'],
      rules: {
        '@typescript-eslint/no-undef': 'off',
      },
    },
  ],
}
```

I'm not an expert on eslint, but this configuration worked for me.

**Comment by boukeversteegh** [comment]
PR ready https://github.com/stephenh/ts-proto/pull/436

**Comment by absoludity** [comment]
Excellent, thanks @boukeversteegh ... now I can just update ts-proto instead :) And thanks for the info about the eslintrc..., I did briefly look for a way to supress it for a particular file, but missed the overrides.

**Comment by absoludity** [comment]
Rubber-stamping this one to unblock changes to proto files.

**Comment by castelblanque** [comment]
@absoludity After this change (containing the upgrade of ts-proto): could we get rid of the generated TS source code for Dashboard?

**Comment by absoludity** [comment]
> @absoludity After this change (containing the upgrade of ts-proto): could we get rid of the generated TS source code for Dashboard?

It's unrelated to this change/upgrade. We may want to do so but that'll be part of the discussion at #3908 .

**Comment by antgamdia** [comment]
Sorry, I've been OOO for a while.

> cc antgamdia I'm not 100%, but it looks like you may have manually updated the generated content in this commit so that it would pass? I thought of doing the same but we need to be able to work with the generated content.

Yep, you're totally right. [I added](https://github.com/kubeapps/kubeapps/pull/3894/commits/dcf07cc2b4b2ea4c91267da647d21a9b0d5cd273#diff-3794f941f1e38cef30a3b20d95a1d241818d2dc31375455fb103b78cfcc7406dR375-R376) a `return undefined` to pass the linter issue (albeit being consistent with the method's signature) after the ts-proto dep upgrade while developing the service account thing. I forgot to look into the issue in-depth and I totally miss that change when committing and sending the PR. My bad. I'm sorry :(

Thanks for catching the issue, Michael, and special thanks to the ts-proto team; what a quick solution!!

**Pull request merged**
