### PR TITLE
Jsonnet support

### PR DESCRIPTION
**Pull request by ngtuna**
This supports deploy kubeapps components via the `kubeapps.jsonnet` file.

```
$ d=$PWD/kubeapps-manifest
$ git clone --recurse-submodules https://github.com/kubeapps/manifest $d
$ export KUBECFG_JPATH=$d/lib:$d/vendor/kubecfg/lib:$d/vendor/ksonnet-lib
$ kubeapps up --file $d/kubeapps.jsonnet
$ kubeapps down --file $d/kubeapps.jsonnet
```

### CODE REVIEW

**Comment by anguslees** [comment]
There's nothing wrong with this PR, but I'm confused where the `kubeapps/installer` codebase is going. We seem to have too many features for experimentation (imo) compared to the final goal as a single-file, just-works installer.

Is the final version going to support external, or internal embedded files?  as YAML, or jsonnet?
Is it intended as a platform for us as devs to easily experiment with new files, or for end users? (does it offer anything beyond what a simple shell script would do for experimentation?)

**Comment by ngtuna** [comment]
> There's nothing wrong with this PR, but I'm confused where the kubeapps/installer codebase is going. We seem to have too many features for experimentation (imo) compared to the final goal as a single-file, just-works installer.

That's true. However, this is not the final state of the kubeapps/installer. I am adding support for `kubeapps.jsonnet` file only for development purpose that means we can update the file and easily try `kubeapps up`. We won't embed the content of it into the installer code at this stage IMO until we release it.

> Is the final version going to support external, or internal embedded files? as YAML, or jsonnet?
Is it intended as a platform for us as devs to easily experiment with new files, or for end users? (does it offer anything beyond what a simple shell script would do for experimentation?)

The final version is for end users and we are already clear about the UX. Right now I am just trying to go over the scope for testing both yaml and jsonnet files. We haven't decided to go with YAML or jsonnet or both yet. I am fine with those options. I won't merge this PR until we agree on supporting jsonnet, otherwise I will just close it.

**Comment by sebgoa** [comment]
@ngtuna we should embed the manifests right now.

it should be a very simple tool with two (maximum three commands): `up` and `dashboard`

The `up` just applys the manifests that are embedded. I don't know if we can embed jsonnet manifests from `kubeapps/manifests` or if those need to be expanded prior to being embedded.

Then we need some minimal testing

**Comment by ngtuna** [comment]
Should be closed now. We can open this discussion and implement in future if we think it's worth to use jsonnet file.

**Pull request closed without merging**
