### PR TITLE
Use new kubeappsapis to perform the package actions 

### LINKED ISSUE #3477: Call new API operations from the UI
I've noticed we didn't have any issue tracking this (apart from the main one).

This issue is to track the status of migrating the UI to make it use the new API for creating, updating, deleting and rolling back applications.

  - [x] https://github.com/kubeapps/kubeapps/pull/3463
  - [x] https://github.com/kubeapps/kubeapps/pull/3476
  - [x] https://github.com/kubeapps/kubeapps/pull/3475
  - [x] https://github.com/kubeapps/kubeapps/pull/3490

### PR DESCRIPTION
**Pull request by antgamdia**
### Description of the change

In this PR we switch from the kubeops endpoint to the new API performing the actions (create, upgrade, delete and rollback)

### Benefits

We will use the new service and will be closer to be able to sunset (at some point) kubeops

### Possible drawbacks

N/A

### Applicable issues

- closes #3477

### Additional information

https://user-images.githubusercontent.com/11535726/134525785-f77ef68b-3888-4c09-b74a-1537755331f6.mp4

This PR is the aggregation of:

- [x] https://github.com/kubeapps/kubeapps/pull/3463
- [x] https://github.com/kubeapps/kubeapps/pull/3475
- [x] https://github.com/kubeapps/kubeapps/pull/3476
- [x] https://github.com/kubeapps/kubeapps/pull/3490

### CODE REVIEW

**Comment by antgamdia** [comment]
Personal note: the rollback operation is not supported for every package, so the UI should be aware of that for deciding whether or not to render the button (the action itself is plugin-awate, but the rendering it is not yet). Implement it before merging the PR.

**Comment by antgamdia** [comment]
Although I initially thought the CI issue was just a problem while upgrading packages, it is not. In fact, it is the "missing permissions" test that is failing. I'm checking the error handling in both front/back end.

**Comment by antgamdia** [comment]
> Personal note: the rollback operation is not supported for every package, so the UI should be aware of that for deciding whether or not to render the button (the action itself is plugin-aware, but the rendering it is not yet). Implement it before merging the PR.

Done :)
image

**Review by absoludity — APPROVED** [review]
I've not reviewed this PR specifically, but but the 4 linked PRs which make up this one, all of which I've +1'd. Assuming it's the same code, +1 :)

**Comment by absoludity** [comment]
> > I've not reviewed this PR specifically, but but the 4 linked PRs which make up this one, all of which I've +1'd. Assuming it's the same code, +1 :)
> 
> I'd say the only new change it has is the conditional rollback button: [b408388](https://github.com/kubeapps/kubeapps/commit/b40838836f0bb746797e387eba4be3386dd45c0c)

Great, thanks. Looks good.

**Pull request merged**
