### PR TITLE
Add details for creating service acc for carvel.

### PR DESCRIPTION
**Pull request by absoludity**
Signed-off-by: Michael Nelson <minelson@vmware.com>

### Description of the change

Adds example for creating the service account to reconcile carvel packages. Also ensures carvel repo is added to the kapp-controller-packaging-global namespace.

cc @raquel-campuzano 

### Benefits

Easier for people to test the carvel support.

### Applicable issues

- fixes #

### CODE REVIEW

**Comment by castelblanque** [comment]
Good addition!
Thanks for differentiating the scenario for `RoleBinding` and `ClusterRoleBinding`.

**Comment by castelblanque** [comment]
It seems there are some conflicts after Pepe's docs restructuring?

**Review by castelblanque — APPROVED** [review]

**Comment by absoludity** [comment]
> It seems there are some conflicts after Pepe's docs restructuring?

Yep, I'll fix those. Thanks.

**Review by antgamdia — APPROVED** [review]
Thanks for the extra info!

**Pull request merged**
