### PR TITLE
Merges kubeapps/manifest repo into kubeapps/kubeapps

### PR DESCRIPTION
**Pull request by prydonius**
- adds new Travis CI config to take advantage of multi-stage concurrent builds for cross-compilation and different components

NOTE: this is supposed to include historical commits from kubeapps/manifest. Please **don't squash and merge** this PR.

### CODE REVIEW

**Comment by sameersbn** [comment]
lgtm!
@ngtuna can you please review the travis spec

**Comment by sameersbn** [comment]
the `scripts/sync-manifest.sh` file can be removed in this change, right?

**Comment by prydonius** [comment]
> the scripts/sync-manifest.sh file can be removed in this change, right?

yep good point!

**Comment by prydonius** [comment]
FYI I tested the CI in my fork: https://github.com/prydonius/kubeapps/releases

**Pull request merged**
