### PR TITLE
Update documentation structure. No file updated/created/deleted

### LINKED ISSUE #4123: Tidy up the `docs` folder
### Description:

As Kubeaps is rapidly evolving, some documentation is becoming outdated. Besides, the current  `docs` folder structure is not the best.

We should come up with a way to quickly be able to look up what we want to; for instance, using more "how-to" docs or following a different folder structure.

This is also related to the #3953 .

### PR DESCRIPTION
**Pull request by ppbaena**
### Description of the change

This is the first PR in order to restructure and update Kubeapps documentation. This PR **only includes changes in the structure** of the documentation, **no file addition/update/deletion**. Main goal is to simplify the review process, so reviewers can initially check, discuss and validate the structure, and then track changes in the different files added, updated and deleted from the documentation. 

Once the structure is validated (**and before merging into main**), it is planned to send a new PR, this time including all updates in files to rename some, but specially to update links according to the new structure.

### Benefits

Better user experience in Kubeapps documentation.

### Possible drawbacks

Broken links from external sites and blog posts pointing to kubeapps documentation according to previous structure.
Those already identified should be requested to be updated (i.e. Kubeapps on TKG post).

### Applicable issues

- fixes #4123 

### Additional information

Documentation structured according [Diátaxis](https://diataxis.fr/) framework.

### CODE REVIEW

**Review by absoludity — APPROVED** [review]
Thanks for getting us started on this Pepe! Sorry I hadn't gotten to it yet.

GitHub doesn't appear to make it easy to just list the main changes for review, but from what I can gather, it's moving the existing docs from `docs/user` and `docs/developer` into `docs/background`, `docs/howto`, `docs/reference` and `docs/tutorial`. Some items seem clear - like moving the `architecture` into `docs/background` (given it's not really current reference) or moving `offline-installation` into `howto`, while some seem a bit harder, but I think that's expected with the docs system (and it'll become clearer as we update the content to match, I assume - inline with https://diataxis.fr/).
 
Question: I'm probably going to regret asking, since it'll have an obvious answer, but what's the `EDR` in `docs/reference/EDR`? (I assume it's not Endpoint Detection and Response :P ).

Just note: Moving some files will require updating references to those files in other code/scripts etc. (eg. `docs/howto/manifests/kubeapps-local-dev-values.yaml`)

Great to see this beginning!

**Comment by ppbaena** [comment]
> GitHub doesn't appear to make it easy to just list the main changes for review, but from what I can gather, it's moving the existing docs from `docs/user` and `docs/developer` into `docs/background`, `docs/howto`, `docs/reference` and `docs/tutorial`. Some items seem clear - like moving the `architecture` into `docs/background` (given it's not really current reference) or moving `offline-installation` into `howto`, while some seem a bit harder, but I think that's expected with the docs system (and it'll become clearer as we update the content to match, I assume - inline with https://diataxis.fr/).

Exactly @absoludity , that's the main goal, start by updating the structure and then continue with a revision of the documentation.

> Question: I'm probably going to regret asking, since it'll have an obvious answer, but what's the `EDR` in `docs/reference/EDR`? (I assume it's not Endpoint Detection and Response :P ).

**EDR** = **E**ngineering **D**ecission **R**ecords 😉 

> Just note: Moving some files will require updating references to those files in other code/scripts etc. (eg. `docs/howto/manifests/kubeapps-local-dev-values.yaml`)

Thanks for the heads up, `/manifests` , `/scripts` and `/examples` folders must be checked.

**Comment by absoludity** [comment]
> Do not merge this branch into main until we have all documentation updates in #4267 validated and merged into this branch.

I assume this is still waiting (no rush, just making sure you're not waiting on input here :) )

**Comment by ppbaena** [comment]
I have included last changes in documentation introduced by @dlaloue-vmware and merged the `doc-update` branch in this branch. It should ready to be merged into main.

**Comment by absoludity** [comment]
> I have included last changes in documentation introduced by @dlaloue-vmware and merged the `doc-update` branch in this branch. It should ready to be merged into main.

We'll just need to sort out the merge conflicts.

**Comment by absoludity** [comment]
Just note Pepe that this PR is currently not targeting the main branch of the kubeapps/kubeapps repo, but rather the `new-doc-structure` branch in the `kubeapps` repo. I'm not sure if that's intended, but guessing not, since you've since merged main into this branch here (`new-doc-structure` in your `ppbaena/kubeapps` repo), but not in the target.

I'm guessing you expected this PR to be targeting main, but I'm not 100%. If so, you can change that by editing it above.

**Review by absoludity — APPROVED** [review]
Great, thanks Pepe for all the conflict resolution. We may find some dead links or small issues, but any fall-out will be easy to fix, and it'll be great to be able to start working with the new structure!

**Pull request merged**
