### PR TITLE
Add security.md

### PR DESCRIPTION
**Pull request by absoludity**
### Description of the change

Just adds a security.md based off a combination of the pinniped and octant projects.

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]

**Comment by antgamdia** [comment]
This is unrelated to the security document itself, but since I've been reviewing the whole set of docs, I noticed the [contributing.md file ](https://github.com/kubeapps/kubeapps/blob/master/CONTRIBUTING.md#enforcement) is still pointing to Ara. 
Perhaps it is the right way, but I just wanted to let you know.

**Comment by andresmgot** [comment]
Good point, we should update that.

**Comment by absoludity** [comment]
Thanks @antgamdia - are you collecting those in a branch? (assuming there's other out-of-date info throughout the docs)

**Comment by antgamdia** [comment]
> Thanks @antgamdia - are you collecting those in a branch? (assuming there's other out-of-date info throughout the docs)

I already pointed out this issue in https://github.com/kubeapps/kubeapps/pull/2134, but we forgot about it and merged it. Currently, I have no active branch on outdated documentation.

**Pull request merged**
