### PR TITLE
Default to the container env proxy vars if none set from apprepo.

### PR DESCRIPTION
**Pull request by absoludity**
Just a follow-up commit that didn't make it into #1966 before it was merged.

### CODE REVIEW

**Review by andresmgot — COMMENTED** [review]
And now the tests are failing :)

**Comment by absoludity** [comment]
> And now the tests are failing :)

Hah, that's interesting. It's failing because the cicircle env actually sets these vars and I hadn't cleared them for the test (only saved and overwrote the ones I was testing).

**Review by andresmgot — APPROVED** [review]

**Comment by absoludity** [comment]
So I'm still not sure I want to land this PR. I'd originally done it because of your [original comment](https://github.com/kubeapps/kubeapps/pull/1966#discussion_r477105304), but after I clarified there, I'm not sure whether you still think it should land. I don't see why we would want this default to env behaviour now (yes, backwards compat, but the change in #1966 already ensures the original intention of #1097 without requiring the manual env ar setting). Let me know what you think.

**Comment by andresmgot** [comment]
It doesn't hut, does it? Is there any drawback of merging this?

**Comment by absoludity** [comment]
> It doesn't hut, does it? Is there any drawback of merging this?

Just extra code which in the future may cause confusion given it's not needed. But OK, I think you think it's worthwhile keeping the backwards compat in case someone is manually doing this. Merging.

**Pull request merged**
