### PR TITLE
MongoDB replacement proposal

### PR DESCRIPTION
**Pull request by andresmgot**
**Description of the change**

This is a design proposal for https://github.com/kubeapps/kubeapps/issues/651

### CODE REVIEW

**Comment by lindhe** [comment]
I see a lot of talk about Redis or Etcd, both of which makes are pitched as _key-value stores_. But when eyeing through the "Current usage" section, my guts don't say key-value store when seeing that content. Much of that looks more complex, e.g. Collections/charts. I understand that it's possible, but are Redis/Etcd the right tools?

I've only read about them, and heard a security talk about Redis, so I'm not really familiar working with them. Maybe my hunch about their intended use is way off. :)

**Comment by andresmgot** [comment]
> I see a lot of talk about Redis or Etcd, both of which makes are pitched as _key-value stores_. But when eyeing through the "Current usage" section, my guts don't say key-value store when seeing that content. Much of that looks more complex, e.g. Collections/charts. I understand that it's possible, but are Redis/Etcd the right tools?
> 
> I've only read about them, and heard a security talk about Redis, so I'm not really familiar working with them. Maybe my hunch about their intended use is way off. :)
> 
> Relevant? https://dzone.com/articles/great-redis-misapprehension

Right, in this case, I believe that Redis is a suitable solution because it's closer to a cache rather than a database, which is similar to our use case. It's true that the data is not that simple so it may not be the best approach.

> With the outlined options, I'd put my vote to postgres :)

I agree: Its support for JSON objects and it's similarity to MongoDB makes it a good fit. We still need to take care of the persistence or HA but it's the less disruptive.

**Comment by andresmgot** [comment]
Updated the document with a final proposal

**Comment by absoludity** [comment]
Thanks for the update. There's nothing stopping this proposal landing right?

**Comment by andresmgot** [comment]
> Thanks for the update. There's nothing stopping this proposal landing right?

I was just waiting for a final _lgtm_ or in case anyone has any other feedback. Merging this then.

**Pull request merged**
