### PR TITLE
Continue to poll for resource references when not found

### PR DESCRIPTION
**Pull request by absoludity**
### Description of the change

This PR updates the AppView so it handles the fetching of the resource references directly (rather than dispatching and going through redux) so that it can decide itself when to poll and importantly, can abort the polling when the component is unmounted.

This fixes a couple of issues that I found recently while testing deploying a flux package with a service account that doesn't have the required RBAC:

1. The existing code would retry the request up to 4 times, then display the not found error. This was find for the case where we expect the resources to exist in a short time-frame, but not for the case where they will never exist until RBAC is updated (see #4337 ),
2. The existing code would continue to retry the request even when you navigated away from the app view. This was because there was not a way currently to abort the requests when they are abstracted away through the redux dispatch/state-update lifecycle.

Since the direction of React's function components with `useEffect` etc. seems to be encouraging local state (rather than requiring redux for global state), I updated the component to request the refs directly and use local state. 

### Benefits

People won't be confronted with a NotFound error when viewing the detail of an installed app that is pending due to insufficient RBAC.

### Possible drawbacks

Testing components that manage local state via async network requests is more challenging (had to re-read about `async act()` to understand why components weren't rendered in tests etc.).

### Applicable issues

- ref #3695

### CODE REVIEW

**Comment by castelblanque** [comment]
Excellent!, it made me reread about React's `act` too -> `This makes your test run closer to how React works in the browser.` 🤔 
Just a question: why not using one of the many retry libraries out there?

**Review by castelblanque — APPROVED** [review]

**Comment by absoludity** [comment]
Thanks for the review :)

> Just a question: why not using one of the many retry libraries out there?

I did check if lodash already has something I can use (since we already import lodash), but didn't find one. Otherwise, I'm a bit hesitant to import something like https://www.npmjs.com/package/async-retry without seeing a benefit (try re-writing the small change in AppView.ts to use it). If we were using retries in multiple places, I'd definitely see the worth in pulling out the shared functionality and perhaps using async-retry. Let me know if there's a benefit I'm missing for a single case like this?

**Comment by castelblanque** [comment]
> Let me know if there's a benefit I'm missing for a single case like this?

Once the code is written, no benefit in switching back to a library.
The way I see it, sometimes even for a single case it is worth using one library: your project's code focuses on the core business, might take advantage of additional features (e.g. exponential backoff), or even increase readability (e.g. code block should be shorter).

**Comment by absoludity** [comment]
> > Let me know if there's a benefit I'm missing for a single case like this?
> 
> Once the code is written, no benefit in switching back to a library. The way I see it, sometimes even for a single case it is worth using one library: your project's code focuses on the core business, might take advantage of additional features (e.g. exponential backoff), or even increase readability (e.g. code block should be shorter).

Yep, agree if there's increased readability and/or additional features that are needed it'd be worth it, just don't see that here at all (tried re-writing as above, harder to see, because it's more generic, and we don't want exp backoff or anything similar as it needs to respond quickly when the installed package is created).

**Pull request merged**
