### PR TITLE
Bump postgresql dependency and adapt README.md in the Helm Chart

### PR DESCRIPTION
**Pull request by miguelaeh**
### Description of the change
We are changing master and slave by primary and read replica in the PostgreSQL chart. This PR bumps the PostgreSQL dependency and adapts the README.md.

Probably we want to add to this major version the changes for Helm v3 too.

### Applicable issues

  - fixes #

### CODE REVIEW

**Comment by andresmgot** [comment]
is that version already available? The CI is failing:

```
Save error occurred:  could not find : chart postgresql not found in https://charts.bitnami.com/bitnami
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : chart postgresql not found in https://charts.bitnami.com/bitnami
```

**Comment by miguelaeh** [comment]
No, sorry, I forgot to tell that. Were are working to release it.

**Comment by andresmgot** [comment]
okay, we are preparing a new release now too so this change is better to be merged afterwards.

**Comment by carrodher** [comment]
@andresmgot @miguelaeh can you close this PR in favor of #2157? We are doing the major version bump (also the bundled postgresql) in the previous one

**Comment by miguelaeh** [comment]
Closing it, also we just noticed this is wrong anyway, the `To 2.0` section should not be changed.

**Pull request closed without merging**
